  /* login*/
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

/*loadin*/ 
export const SET_AUTENTICACION_CARGANDO = 'SET_AUTENTICACION_CARGANDO';
export const REMOVE_AUTENTICACION_CARGANDO = 'REMOVE_AUTENTICACION_CARGANDO';


/*user loaded*/
export const USUARIO_CARGADO_SUCCES = 'USUARIO_CARGADO_SUCCES';
export const USUARIO_CARGADO_FAIL = 'USUARIO_CARGADO_FAIL';


/* autenticado */ 
export const AUTHENTICACION_SUCCESS = 'AUTHENTICACION_SUCCESS';
export const AUTHENTICACION_FAIL = 'AUTHENTICACION_FAIL';

/*reset password*/ 
export const RESETEO_PASSWORD_SUCCESS = 'RESETEO_PASSWORD_SUCCESS';
export const RESETEO_PASSWORD_FAIL = 'RESETEO_PASSWORD_FAIL';
export const CONFIRMACION_RESETEO_PASSWORD_SUCCESS = 'CONFIRMACION_RESETEO_PASSWORD_SUCCESS';
export const CONFIRMACION_RESETEO_PASSWORD_FAIL = 'CONFIRMACION_RESETEO_PASSWORD_FAIL';

/* refresh */ 
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAIL = 'REFRESH_FAIL';

/* alertas */ 
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

/* Cursos*/
export const GET_CURSOS_SUCCESS = 'GET_CURSOS_SUCCESS';
export const GET_CURSOS_FAIL = 'GET_CURSOS_FAIL';
export const GET_CURSO_FAIL = 'GET_CURSO_FAIL';
export const GET_CURSO_SUCCESS = 'GET_CURSO_SUCCESS';

/* Noticias*/
export const GET_NOTICIAS_SUCCESS = 'GET_NOTICIAS_SUCCESS';
export const GET_NOTICIAS_FAIL = 'GET_NOTICIAS_FAIL';


/* Reserva  */
export const RESERVA_HORARIO_SUCCESS = 'RESERVA_HORARIO__SUCCESS';
export const RESERVA_HORARIO_FAIL = 'RESERVA_HORARIO_FAIL';
export const GET_RESERVA_HORARIO_SUCCESS = 'GET_RESERVA_HORARIO__SUCCESS';
export const GET_RESERVA_HORARIO_FAIL = 'GET_RESERVA_HORARIO_FAIL';
export const ELIMINAR_RESERVA_SUCCESS = 'ELIMINAR_RESERVA_SUCCESS';
export const ELIMINAR_RESERVA_FAIL = 'ELIMINAR_RESERVA_FAIL';


/* ingresos */
export const GET_INGRESOS_SUCCESS = 'GET_INGRESOS_SUCCESS';
export const GET_INGRESOS_FAIL = 'GET_INGRESOS_FAIL';

/*pagos*/
export const GET_PAGOS_SUCCESS = 'GET_PAGOS_SUCCESS'
export const GET_PAGOS_FAIL = 'GET_PAGOS_FAIL'

