# Generated by Django 4.0.6 on 2022-08-15 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('cuposLibres', models.PositiveSmallIntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('costo', models.PositiveSmallIntegerField()),
                ('descripcion', models.TextField(max_length=250)),
                ('categoria', models.CharField(choices=[('A', 'Ejercicio físico'), ('B', 'Cardio'), ('C', 'Danza')], default='A', max_length=1)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.horario')),
            ],
        ),
    ]
