# Generated by Django 4.0.6 on 2022-08-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='horario',
            name='cuposLibres',
            field=models.PositiveSmallIntegerField(default=40),
        ),
    ]
