# Generated by Django 4.0.6 on 2022-08-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0002_remove_cursos_categoria_alter_horario_cuposlibres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
        migrations.AddField(
            model_name='cursos',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
