# Generated by Django 4.0.6 on 2022-08-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0004_alter_cursos_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='horario',
        ),
        migrations.AddField(
            model_name='cursos',
            name='horario',
            field=models.ManyToManyField(to='Cursos.horario'),
        ),
    ]
