# Generated by Django 4.0.6 on 2022-09-02 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0003_remove_usuarios_curso'),
        ('Cursos', '0005_remove_cursos_horario_cursos_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaCursoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CursoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupo', models.PositiveSmallIntegerField(default=40)),
                ('dia', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='cuposLibres',
        ),
        migrations.AddField(
            model_name='cursos',
            name='horarios',
            field=models.ManyToManyField(through='Cursos.CursoHorario', to='Cursos.horario'),
        ),
        migrations.AddField(
            model_name='cursos',
            name='usuarios',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cursohorario',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.cursos'),
        ),
        migrations.AddField(
            model_name='cursohorario',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.horario'),
        ),
        migrations.AddField(
            model_name='cursohorario',
            name='usuario',
            field=models.ManyToManyField(through='Cursos.AsistenciaCursoUsuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistenciacursousuario',
            name='curso_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.cursohorario'),
        ),
        migrations.AddField(
            model_name='asistenciacursousuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
