# Generated by Django 4.0.6 on 2022-09-07 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0003_remove_usuarios_curso'),
        ('Cursos', '0007_alter_cursohorario_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_de_pago', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='cursos',
            name='pagos_cuotas',
            field=models.ManyToManyField(related_name='pagos', through='Cursos.PagoCuota', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cursohorario',
            name='dia',
            field=models.CharField(choices=[('Lu', 'Lunes'), ('Ma', 'Martes'), ('Mi', 'Miercoles'), ('Ju', 'Jueves'), ('Vi', 'Viernes'), ('Sa', 'Sabado')], max_length=200),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='usuarios',
            field=models.ManyToManyField(related_name='cursos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagocuota',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.cursos'),
        ),
        migrations.AddField(
            model_name='pagocuota',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
