# Generated by Django 4.0.6 on 2022-09-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0008_pagocuota_cursos_pagos_cuotas_alter_cursohorario_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocuota',
            name='dia_de_pago',
            field=models.DateField(),
        ),
    ]
