# Generated by Django 4.0.6 on 2022-09-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0011_remove_cursohorario_usuario_cursos_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='imagen',
            field=models.ImageField(default='cursos/imagenes/sparta_img.jpg', null=True, upload_to='cursos/imagenes/', verbose_name='Imagen de portada'),
        ),
    ]
