# Generated by Django 4.0.6 on 2022-10-05 03:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_usuarios_pago_cuota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cursos', '0013_alter_cursohorario_dia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cursos',
            new_name='Curso',
        ),
    ]
