# Generated by Django 4.0.6 on 2022-10-05 22:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0014_rename_cursos_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, max_length=400, null=True),
        ),
    ]
