# Generated by Django 4.0.6 on 2022-10-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0017_alter_curso_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocuota',
            name='monto_final',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagocuota',
            name='recargo',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
