# Generated by Django 4.0.6 on 2022-10-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0018_pagocuota_monto_final_pagocuota_recargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocuota',
            name='recargo',
            field=models.BooleanField(default=False, help_text='Marque la casilla si desea aplicar el recargo al pago'),
        ),
    ]
