# Generated by Django 4.0.6 on 2022-10-20 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0020_alter_curso_nombre_alter_curso_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursohorario',
            options={'ordering': ['dia']},
        ),
    ]
