# Generated by Django 4.0.6 on 2022-10-28 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cursos', '0021_alter_cursohorario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursohorario',
            options={'ordering': ['dia', 'horario__horaInicio']},
        ),
        migrations.AlterModelOptions(
            name='pagocuota',
            options={'ordering': ['dia_de_pago']},
        ),
        migrations.AlterField(
            model_name='curso',
            name='state',
            field=models.BooleanField(default=True, help_text='Si desactiva el curso este no se mostrara en la pagina principal', verbose_name='Activar/Desactivar'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='cursos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cursohorario',
            name='dia',
            field=models.CharField(choices=[('1-Lunes', 'Lunes'), ('2-Martes', 'Martes'), ('3-Miercoles', 'Miercoles'), ('4-Jueves', 'Jueves'), ('5-Viernes', 'Viernes'), ('6-Sabado', 'Sabado')], max_length=200),
        ),
    ]
