# Generated by Django 4.0.6 on 2022-10-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0022_alter_cursohorario_options_alter_pagocuota_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
