# Generated by Django 4.0.6 on 2022-10-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0023_curso_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocuota',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
