# Generated by Django 4.0.6 on 2022-11-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0024_pagocuota_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['horaInicio'], 'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(default='cursos/imagenes/logoo.jpg', null=True, upload_to='cursos/imagenes/', verbose_name='Imagen de portada'),
        ),
    ]
