# Generated by Django 4.0.6 on 2023-04-23 03:34

import Cursos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0025_alter_horario_options_alter_curso_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='vencimiento_cuota',
            field=models.DateField(default=Cursos.models.calcular_fecha_vencimiento),
        ),
    ]
