# Generated by Django 4.0.6 on 2022-08-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='noticia',
            managers=[
            ],
        ),
    ]
