# Generated by Django 4.0.6 on 2022-09-29 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0002_alter_noticia_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='slug',
        ),
    ]
