# Generated by Django 4.0.6 on 2022-10-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0004_alter_noticia_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
