# Generated by Django 4.0.6 on 2022-07-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('pellido', models.CharField(max_length=250)),
                ('cedula', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
                ('esta_activo', models.BooleanField(default=True)),
            ],
        ),
    ]
