# Generated by Django 4.0.6 on 2022-07-24 00:51

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuarios',
            managers=[
                ('objectos', django.db.models.manager.Manager()),
            ],
        ),
    ]
