# Generated by Django 4.0.6 on 2022-07-25 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_usuarios_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='pellido',
            new_name='apellido',
        ),
    ]
