# Generated by Django 4.0.6 on 2022-09-01 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_usuarios_pago_cuota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='curso',
        ),
    ]
