# Generated by Django 4.0.6 on 2022-09-24 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0012_alter_cursos_imagen'),
        ('Users', '0003_remove_usuarios_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.cursohorario')),
            ],
        ),
        migrations.AddField(
            model_name='usuarios',
            name='reservas',
            field=models.ManyToManyField(blank=True, related_name='reserva', through='Users.ReservaUsuarios', to='Cursos.cursohorario'),
        ),
        migrations.AddField(
            model_name='reservausuarios',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
