# Generated by Django 4.0.6 on 2022-10-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_usuarios_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='cedula',
            new_name='documento',
        ),
    ]
