# Generated by Django 4.0.6 on 2022-10-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_alter_usuarios_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
