# Generated by Django 4.0.6 on 2022-11-30 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_usuarios_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='is_deleted',
        ),
    ]
